### ISSUE TITLE
개발 전 환경설정

### ISSUE THREAD

**Issue by boraJeon** [boraJeon/what-to-do#1]
- [x] cocoaPods설치
- [x] 새로운 프로젝트 생성(Xcode)
- [x] Firebase에 ios 프로젝트 생성 & firebase 설치   
- [x] fabric 설치 
- [x] Alamofire

**Comment by boraJeon** [comment]
Carthage 설치 및 테스트

**Comment by ChangJoo-Park** [comment]
이슈의 body 부분에 `- [ ] `로 하위 작업을 만들어보세요

**Comment by boraJeon** [comment]
carthage를 사용하려고 하였으나 firebase를 설치하려면(firebase의 인증방식을 사용하기위해) carthage를 지원하지 않아 cocoapods로 변경 결정

**Comment by ChangJoo-Park** [comment]
기본적으로 지원할거같은데 아니었네요

https://github.com/firebase/firebase-ios-sdk/issues/9

아직 열려있어요

**Comment by boraJeon** [comment]
@ChangJoo-Park 헛.. 근데 왜 공식사이트엔 해당 내용이 추가되어있지 않은걸까요? 보니깐 작년 5월이네요 ㅎㄷㄷ

**Comment by boraJeon** [comment]
다시 carthage로 설치하여 적용하려고하였으나 예전에도 발생하였던 비슷한 에러로 인해 막혀버림..
원인이 뭔지 도통 파악이 안된다 ㄷㄷ 
뭔가 경로 설정을 다시 해줘야하는것인가..?
나중에 다시 찬찬히 봐야겠다 ㅠ_ㅠ


*** **xcodebuild output can be found in /var/folders/1j/9m1hdhts24j_cr_rsyjpx3l40000gn/T/carthage-xcodebuild.M2ZE4.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/tabling/Desktop/Tabling/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH**
